#!/usr/bin/env perl

use warnings;

open $fh, '+<', "README.md" or die $!;

SCAN_SECTION:
while(<$fh>)
{
	if(/^#+ CLI options \((.+?)\)/)
	{
		my $prog = $1;
		warn "insert $prog usage help ...\n";
		my $insert_pos = undef;
		SCAN_CODEBLOCK:
		while(<$fh>)
		{
			if($_ eq '```'."\n")
			{
				if(not defined $insert_pos)
				{
					$insert_pos = tell $fh;
				}
				else
				{
					$/ = undef;
					$document_rest = $_ . <$fh>;
					$/ = "\n";
					
					seek $fh, $insert_pos, 0 or die $!;
					
					$ENV{'LANGUAGE'} = 'C';
					open $ph, '-|', "./".$prog, "--help" or die $!;
					print {$fh} <$ph>;
					my $continue_pos = tell $fh;
					
					print {$fh} $document_rest;
					truncate $fh, tell $fh;
					seek $fh, $continue_pos, 0 or die $!;
					last SCAN_CODEBLOCK;
				}
			}
		}
	}
}

close $fh or die $!;
