#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
	if [ -x "`which update-menus 2>/dev/null`" ]
	then
		update-menus
	fi
	if [ -x "`which update-desktop-database 2>/dev/null`" ]
	then
		update-desktop-database
	fi
fi
